//! 生成一个用于手工测试 git-pincer 的临时演练仓库。
//!
//! ```bash
//! cargo run --example playground            # 生成到 /tmp/git-pincer-playground
//! cargo run --example playground -- <path>  # 生成到指定目录
//! ```
//!
//! 仓库内置全部冲突场景:merge(多文件 + 二进制)、rebase(两轮)、
//! cherry-pick、revert 以及 file 模式样例。生成完成后打印各场景的
//! 测试命令;重复运行会安全地重建仓库(通过标记文件识别,避免误删)。

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};

/// 标记文件名:用于识别目录是否由本示例生成,避免误删用户数据。
const MARKER: &str = ".git-pincer-playground";

fn main() -> Result<()> {
    let dir = target_dir();
    prepare_dir(&dir)?;
    build_repo(&dir)?;
    print_guide(&dir);
    Ok(())
}

/// 解析目标目录:优先取命令行第一个参数,否则用系统临时目录下的固定路径。
fn target_dir() -> PathBuf {
    if let Some(arg) = std::env::args().nth(1) {
        return PathBuf::from(arg);
    }
    if cfg!(unix) {
        PathBuf::from("/tmp/git-pincer-playground")
    } else {
        std::env::temp_dir().join("git-pincer-playground")
    }
}

/// 准备目标目录:已存在且带标记文件则整体重建,否则拒绝覆盖。
fn prepare_dir(dir: &Path) -> Result<()> {
    if dir.exists() {
        if !dir.join(MARKER).exists() {
            bail!(
                "目录 {} 已存在且不是本示例生成的演练仓库,请换一个路径或手动删除后重试",
                dir.display()
            );
        }
        println!("[0/6] 检测到旧演练仓库,重建 {}", dir.display());
        fs::remove_dir_all(dir).context("删除旧演练仓库失败")?;
    }
    fs::create_dir_all(dir).context("创建目标目录失败")?;
    fs::write(
        dir.join(MARKER),
        "generated by `cargo run --example playground`\n",
    )?;
    Ok(())
}

/// 在指定目录执行一条 git 命令,失败时返回携带 stderr 的错误。
///
/// 清除宿主仓库可能注入的 GIT_* 环境变量(与集成测试同款处理),
/// 避免从钩子等嵌套环境运行时被劫持到错误的仓库。
fn git(dir: &Path, args: &[&str]) -> Result<()> {
    let mut cmd = Command::new("git");
    cmd.arg("-C").arg(dir).args(args);
    for var in [
        "GIT_DIR",
        "GIT_WORK_TREE",
        "GIT_INDEX_FILE",
        "GIT_OBJECT_DIRECTORY",
    ] {
        cmd.env_remove(var);
    }
    let out = cmd
        .output()
        .context("无法执行 git,请确认已安装并在 PATH 中")?;
    if !out.status.success() {
        bail!(
            "git {} 失败: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

/// 暂存全部改动并提交。
fn commit_all(dir: &Path, msg: &str) -> Result<()> {
    git(dir, &["add", "-A"])?;
    git(dir, &["commit", "-qm", msg])
}

/// 写入仓库内的一个文本文件。
fn write(dir: &Path, rel: &str, content: &str) -> Result<()> {
    fs::write(dir.join(rel), content).with_context(|| format!("写入 {rel} 失败"))
}

/// 搭建演练仓库:基础提交 + main 演进 + 三个冲突特性分支。
fn build_repo(dir: &Path) -> Result<()> {
    println!("[1/6] 初始化仓库(局部配置身份,关闭签名与钩子)");
    git(dir, &["init", "-qb", "main"])?;
    git(dir, &["config", "user.name", "Playground"])?;
    git(dir, &["config", "user.email", "playground@example.com"])?;
    git(dir, &["config", "commit.gpgsign", "false"])?;
    git(dir, &["config", "core.autocrlf", "false"])?;
    git(dir, &["config", "core.hooksPath", ".git/no-hooks"])?;

    println!("[2/6] 提交基础版本并切出特性分支");
    write(
        dir,
        ".gitignore",
        &format!("{MARKER}\nconflict-marked.txt\n"),
    )?;
    write(
        dir,
        "hello.rs",
        &hello_rs(
            GREET_BASE,
            CONFIG_BASE,
            LOG_BASE,
            VERSION_OLD,
            FAREWELL_BASE,
        ),
    )?;
    write(dir, "notes.txt", &notes(HEAD_BASE, TAIL_BASE))?;
    fs::write(dir.join("logo.bin"), logo(1))?;
    commit_all(dir, "chore: playground base")?;
    for branch in ["feature/merge", "feature/rebase", "feature/cherry"] {
        git(dir, &["branch", branch])?;
    }

    println!("[3/6] 演进 main 分支(两个提交,打 revert-me 标签)");
    write(
        dir,
        "hello.rs",
        &hello_rs(
            GREET_MAIN_V1,
            CONFIG_BASE,
            LOG_MAIN,
            VERSION_NEW,
            FAREWELL_MAIN,
        ),
    )?;
    write(dir, "notes.txt", &notes(HEAD_MAIN, TAIL_BASE))?;
    fs::write(dir.join("logo.bin"), logo(2))?;
    commit_all(dir, "feat: main line updates")?;
    git(dir, &["tag", "revert-me"])?;
    write(
        dir,
        "hello.rs",
        &hello_rs(
            GREET_MAIN_V2,
            CONFIG_BASE,
            LOG_MAIN,
            VERSION_NEW,
            FAREWELL_MAIN,
        ),
    )?;
    commit_all(dir, "feat: refine greeting on main")?;

    println!("[4/6] 构造 feature/merge(与 main 冲突:文本 x2 + 二进制)");
    git(dir, &["switch", "-q", "feature/merge"])?;
    write(
        dir,
        "hello.rs",
        &hello_rs(
            GREET_FEATURE,
            CONFIG_FEATURE,
            LOG_BASE,
            VERSION_NEW, // 与 main 改动一致,形成 Agree 块
            FAREWELL_FEATURE,
        ),
    )?;
    write(dir, "notes.txt", &notes(HEAD_FEATURE, TAIL_BASE))?;
    fs::write(dir.join("logo.bin"), logo(3))?;
    commit_all(dir, "feat: feature branch updates")?;

    println!("[5/6] 构造 feature/rebase(两轮冲突)与 feature/cherry");
    git(dir, &["switch", "-q", "feature/rebase"])?;
    write(
        dir,
        "hello.rs",
        &hello_rs(
            GREET_REBASE,
            CONFIG_BASE,
            LOG_BASE,
            VERSION_OLD,
            FAREWELL_BASE,
        ),
    )?;
    commit_all(dir, "feat: rebase round one (hello.rs)")?;
    write(dir, "notes.txt", &notes(HEAD_REBASE, TAIL_BASE))?;
    commit_all(dir, "feat: rebase round two (notes.txt)")?;
    git(dir, &["switch", "-q", "feature/cherry"])?;
    write(dir, "notes.txt", &notes(HEAD_CHERRY, TAIL_CHERRY))?;
    commit_all(dir, "feat: cherry commit")?;

    println!("[6/6] 回到 main,写入 file 模式样例(conflict-marked.txt)");
    git(dir, &["switch", "-q", "main"])?;
    write(dir, "conflict-marked.txt", CONFLICT_MARKED)?;
    Ok(())
}

// ---- hello.rs 各区域的内容变体 ----
// 区域之间以足量未改动行隔开,保证 TUI 中折叠(z 键)可见:
// greet    双方均改 → Conflict     config 仅 feature 改 → Theirs
// log      仅 main 改 → Ours       version 双方改动一致 → Agree
// farewell 双方均改 → Conflict

const GREET_BASE: &str = r#"    format!("Hello, {name}!")"#;
const GREET_MAIN_V1: &str = r#"    format!("Good morning, {name}!")"#;
const GREET_MAIN_V2: &str = r#"    format!("Good morning, {name}. Welcome back!")"#;
const GREET_FEATURE: &str = r#"    format!("Hey {name}, ready to merge?")"#;
const GREET_REBASE: &str = r#"    format!("Ahoy, {name}!")"#;

const CONFIG_BASE: &str = r#"    "/etc/playground.toml""#;
const CONFIG_FEATURE: &str = r#"    "/etc/playground/config.toml""#;

const LOG_BASE: &str = r#"    "info""#;
const LOG_MAIN: &str = r#"    "debug""#;

const VERSION_OLD: &str = r#"pub const VERSION: &str = "0.1.0";"#;
const VERSION_NEW: &str = r#"pub const VERSION: &str = "0.2.0";"#;

const FAREWELL_BASE: &str = r#"    println!("Bye, {name}.");"#;
const FAREWELL_MAIN: &str = r#"    println!("See you, {name}.");"#;
const FAREWELL_FEATURE: &str = r#"    println!("Farewell, {name}!");"#;

/// 生成 hello.rs 的一个变体:五个可变区域由参数决定,
/// 区域之间是各变体间保持一致的常量填充块。
fn hello_rs(greet: &str, config: &str, log: &str, version: &str, farewell: &str) -> String {
    let mut s = String::from("//! Playground demo file for git-pincer.\n\n");
    s.push_str("/// Greeting entry.\npub fn greet(name: &str) -> String {\n");
    s.push_str(greet);
    s.push_str("\n}\n\n");
    s.push_str(&filler('A'));
    s.push_str("/// Config file location.\npub fn config_path() -> &'static str {\n");
    s.push_str(config);
    s.push_str("\n}\n\n");
    s.push_str(&filler('B'));
    s.push_str("/// Default log level.\npub fn log_level() -> &'static str {\n");
    s.push_str(log);
    s.push_str("\n}\n\n");
    s.push_str(&filler('C'));
    s.push_str("/// Crate version.\n");
    s.push_str(version);
    s.push_str("\n\n");
    s.push_str(&filler('D'));
    s.push_str("/// Farewell message.\npub fn farewell(name: &str) {\n");
    s.push_str(farewell);
    s.push_str("\n}\n");
    s
}

/// 生成一段所有变体间保持不变的常量填充块(约 12 行)。
fn filler(prefix: char) -> String {
    let mut s = format!("// ---- section {prefix}: stable filler ----\n");
    for i in 1..=10 {
        s.push_str(&format!("pub const {prefix}{i:02}: u32 = {i};\n"));
    }
    s.push('\n');
    s
}

// ---- notes.txt 的首行 / 末行变体(中间三行保持不变) ----

const HEAD_BASE: &str = "topic: merge drills";
const HEAD_MAIN: &str = "topic: merge drills (main)";
const HEAD_FEATURE: &str = "topic: merge drills (feature)";
const HEAD_REBASE: &str = "topic: merge drills (rebase)";
const HEAD_CHERRY: &str = "topic: merge drills (cherry)";
const TAIL_BASE: &str = "memo: base edition";
const TAIL_CHERRY: &str = "memo: cherry extras";

/// 生成 notes.txt 的一个变体:首行与末行可变,中间行固定。
fn notes(headline: &str, tail: &str) -> String {
    format!(
        "{headline}\nplan: keep the demo tiny\nowner: playground\nstatus: in progress\n{tail}\n"
    )
}

/// 生成含 NUL 字节的伪二进制内容,seed 不同则内容不同(用于二进制冲突)。
fn logo(seed: u8) -> Vec<u8> {
    let mut bytes = vec![0x89, b'B', b'I', b'N', 0x00, 0x0D, 0x0A];
    for i in 0..24u8 {
        bytes.push(seed.wrapping_mul(31).wrapping_add(i));
        bytes.push(0);
    }
    bytes
}

/// file 模式样例:带标准冲突标记的独立文件(不依赖 git)。
const CONFLICT_MARKED: &str = r#"[server]
<<<<<<< HEAD
host = "0.0.0.0"
=======
host = "192.168.1.10"
>>>>>>> feature/remote-host
port = 8080

[log]
<<<<<<< HEAD
level = "info"
=======
level = "debug"
>>>>>>> feature/remote-host
format = "plain"
"#;

/// 打印各场景的测试命令速查。
fn print_guide(dir: &Path) {
    let d = dir.display();
    println!(
        r#"
✔ 演练仓库已生成:{d}

  cd {d}

── merge:3 个冲突文件(hello.rs 含 Conflict/Ours/Theirs/Agree 各类块,二进制降级选边)
  git-pincer merge feature/merge

── rebase:两轮冲突(先 hello.rs 后 notes.txt)
  git switch feature/rebase && git-pincer rebase main
  # 测完记得 git switch main

── cherry-pick:notes.txt 冲突 + 干净块
  git-pincer cherry-pick feature/cherry

── revert:回滚更早的提交(revert-me 标签)产生冲突
  git-pincer revert revert-me

── file 模式:无需 git,直接解析冲突标记
  git-pincer file conflict-marked.txt

提示:
- 每个场景测完可用 `git-pincer abort` 回到干净状态;
- 重新运行本示例可随时整体重置仓库;
- 未安装二进制时可在项目目录用:cargo run -- -C {d} merge feature/merge"#
    );
}
